//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Dagger_prefab
    {
        public const string BundleName = "dagger_prefab";
        public const string MELEEWEAPON = "MeleeWeapon";
    }
    public class Gameprefab
    {
        public const string BundleName = "gameprefab";
        public const string CLOD = "Clod";
        public const string AGGRESSIVEFISH = "AggressiveFish";
        public const string NORMALFISH = "NormalFish";
        public const string DESTRUCTIBLEITEM = "DestructibleItem";
        public const string DAVE = "Dave";
        public const string TREASURECHEST = "TreasureChest";
        public const string FISHFORK = "FishFork";
    }
    public class Icon
    {
        public const string BundleName = "icon";
        public const string CLOD = "Clod";
        public const string COPPER = "copper";
        public const string CORAL = "Coral";
        public const string CORDAGE = "Cordage";
        public const string HIGHTLIGHTICON = "hightLightIcon";
        public const string KELP = "Kelp";
        public const string NORMALFISH = "NormalFish";
        public const string RANGEICON = "RangeIcon";
        public const string SALT = "Salt";
        public const string SINGLEICON = "SingleIcon";
        public const string TREASURECHESTS = "TreasureChests";
        public const string VINEGAR = "Vinegar";
        public const string WOOD = "Wood";
    }
    public class Pickupitem_prefab
    {
        public const string BundleName = "pickupitem_prefab";
        public const string DROPITEM = "DropItem";
    }
    public class Pteriosfish_aseprite
    {
        public const string BundleName = "pteriosfish_aseprite";
        public const string AGGRESSIVEFISH = "AggressiveFish";
    }
    public class Rifle_prefab
    {
        public const string BundleName = "rifle_prefab";
        public const string GUN = "Gun";
    }
    public class Uigameglobalpanel_prefab
    {
        public const string BundleName = "uigameglobalpanel_prefab";
        public const string UIGAMEGLOBALPANEL = "UIGameGlobalPanel";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePassPanel";
    }
    public class Uigameshippanel_prefab
    {
        public const string BundleName = "uigameshippanel_prefab";
        public const string UIGAMESHIPPANEL = "UIGameShipPanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
    public class Uigamesushipanel_prefab
    {
        public const string BundleName = "uigamesushipanel_prefab";
        public const string UIGAMESUSHIPANEL = "UIGamesushiPanel";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
        public const string UIMAPEDITOR = "UIMapEditor";
    }
}
